//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Runtime Version:4.0.30319.42000
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKHOSTING.UI.Resources {
	using System;
	using System.Reflection;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class Strings {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Strings() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OKHOSTING.UI.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to False.
		/// </summary>
		public static string OKHOSTING_UI_Controls_Forms_BoolField_False {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Controls_Forms_BoolField_False", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to True.
		/// </summary>
		public static string OKHOSTING_UI_Controls_Forms_BoolField_True {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Controls_Forms_BoolField_True", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Left.
		/// </summary>
		public static string OKHOSTING_UI_Controls_Forms_CaptionPosition_Left {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Controls_Forms_CaptionPosition_Left", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Top.
		/// </summary>
		public static string OKHOSTING_UI_Controls_Forms_CaptionPosition_Top {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Controls_Forms_CaptionPosition_Top", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to -.
		/// </summary>
		public static string OKHOSTING_UI_Controls_Forms_EmptyValue {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Controls_Forms_EmptyValue", resourceCulture);
			}
		}
	}
}
