//------------------------------------------------------------------------------
// <auto-generated>
//	 Este código fue generado por una herramienta.
//	 Versión de runtime:4.0.30319.42000
//
//	 Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//	 se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKHOSTING.UI.Security.Resources {
	using System;
	using System.Reflection;
	
	
	/// <summary>
	///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
	/// </summary>
	// StronglyTypedResourceBuilder generó automáticamente esta clase
	// a través de una herramienta como ResGen o Visual Studio.
	// Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
	// con la opción /str o recompile su proyecto de VS.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Strings {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Strings() {
		}
		
		/// <summary>
		///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OKHOSTING.UI.Security.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
		///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Current password.
		/// </summary>
		internal static string OKHOSTING_UI_Security_Controllers_ChangePassword_CurrentPassword {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_Controllers_ChangePassword_CurrentPassword", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a New password.
		/// </summary>
		internal static string OKHOSTING_UI_Security_Controllers_ChangePassword_NewPassword {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_Controllers_ChangePassword_NewPassword", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Repeat new password.
		/// </summary>
		internal static string OKHOSTING_UI_Security_Controllers_ChangePassword_NewPassword2 {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_Controllers_ChangePassword_NewPassword2", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Change password.
		/// </summary>
		internal static string OKHOSTING_UI_Security_Controllers_ChangePassword_Title {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_Controllers_ChangePassword_Title", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Cancel.
		/// </summary>
		internal static string OKHOSTING_UI_Security_LoginController_Cancel {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_LoginController_Cancel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Login.
		/// </summary>
		internal static string OKHOSTING_UI_Security_LoginController_Login {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_LoginController_Login", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Username or password are incorrect, please try again.
		/// </summary>
		internal static string OKHOSTING_UI_Security_LoginController_LoginError {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_LoginController_LoginError", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Password.
		/// </summary>
		internal static string OKHOSTING_UI_Security_LoginController_Password {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_LoginController_Password", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Please login.
		/// </summary>
		internal static string OKHOSTING_UI_Security_LoginController_Title {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_LoginController_Title", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Username.
		/// </summary>
		internal static string OKHOSTING_UI_Security_LoginController_UserName {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_LoginController_UserName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Permission.
		/// </summary>
		internal static string OKHOSTING_UI_Security_Permission {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_Permission", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Allow delete.
		/// </summary>
		internal static string OKHOSTING_UI_Security_Permission_AllowDelete {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_Permission_AllowDelete", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Allowed data type.
		/// </summary>
		internal static string OKHOSTING_UI_Security_Permission_AllowedDataType {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_Permission_AllowedDataType", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Allow insert.
		/// </summary>
		internal static string OKHOSTING_UI_Security_Permission_AllowInsert {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_Permission_AllowInsert", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Allow select.
		/// </summary>
		internal static string OKHOSTING_UI_Security_Permission_AllowSelect {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_Permission_AllowSelect", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Allow update.
		/// </summary>
		internal static string OKHOSTING_UI_Security_Permission_AllowUpdate {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_Permission_AllowUpdate", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Executable methods.
		/// </summary>
		internal static string OKHOSTING_UI_Security_Permission_ExecutableMethods {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_Permission_ExecutableMethods", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Filter.
		/// </summary>
		internal static string OKHOSTING_UI_Security_Permission_Filter {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_Permission_Filter", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Id.
		/// </summary>
		internal static string OKHOSTING_UI_Security_Permission_Id {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_Permission_Id", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Readable members.
		/// </summary>
		internal static string OKHOSTING_UI_Security_Permission_ReadableMembers {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_Permission_ReadableMembers", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Read only members.
		/// </summary>
		internal static string OKHOSTING_UI_Security_Permission_ReadOnlyMembers {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_Permission_ReadOnlyMembers", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Read write members.
		/// </summary>
		internal static string OKHOSTING_UI_Security_Permission_ReadWriteMembers {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_Permission_ReadWriteMembers", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Permission exception.
		/// </summary>
		internal static string OKHOSTING_UI_Security_PermissionException {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_PermissionException", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Data type.
		/// </summary>
		internal static string OKHOSTING_UI_Security_PermissionException_DataType {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_PermissionException_DataType", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Message.
		/// </summary>
		internal static string OKHOSTING_UI_Security_PermissionException_Message {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_PermissionException_Message", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Operation.
		/// </summary>
		internal static string OKHOSTING_UI_Security_PermissionException_Operation {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_PermissionException_Operation", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a User.
		/// </summary>
		internal static string OKHOSTING_UI_Security_PermissionException_User {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_PermissionException_User", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Register.
		/// </summary>
		internal static string OKHOSTING_UI_Security_RegisterController_Register {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_RegisterController_Register", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Register.
		/// </summary>
		internal static string OKHOSTING_UI_Security_RegisterController_Title {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_RegisterController_Title", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Role.
		/// </summary>
		internal static string OKHOSTING_UI_Security_Role {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_Role", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Administrators.
		/// </summary>
		internal static string OKHOSTING_UI_Security_Role_Administrators {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_Role_Administrators", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Db permissions.
		/// </summary>
		internal static string OKHOSTING_UI_Security_Role_DbPermissions {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_Role_DbPermissions", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Everyone.
		/// </summary>
		internal static string OKHOSTING_UI_Security_Role_Everyone {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_Role_Everyone", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Role permission.
		/// </summary>
		internal static string OKHOSTING_UI_Security_RolePermission {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_RolePermission", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Role.
		/// </summary>
		internal static string OKHOSTING_UI_Security_RolePermission_Role {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_RolePermission_Role", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a User.
		/// </summary>
		internal static string OKHOSTING_UI_Security_User {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_User", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Administrator.
		/// </summary>
		internal static string OKHOSTING_UI_Security_User_Administrator {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_User_Administrator", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Anonimous.
		/// </summary>
		internal static string OKHOSTING_UI_Security_User_Anonimous {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_User_Anonimous", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Bypass security.
		/// </summary>
		internal static string OKHOSTING_UI_Security_User_BypassSecurity {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_User_BypassSecurity", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Current.
		/// </summary>
		internal static string OKHOSTING_UI_Security_User_Current {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_User_Current", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Custom permissions.
		/// </summary>
		internal static string OKHOSTING_UI_Security_User_CustomPermissions {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_User_CustomPermissions", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Db permissions.
		/// </summary>
		internal static string OKHOSTING_UI_Security_User_DbPermissions {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_User_DbPermissions", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Effective permissions.
		/// </summary>
		internal static string OKHOSTING_UI_Security_User_EffectivePermissions {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_User_EffectivePermissions", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Is anonimous.
		/// </summary>
		internal static string OKHOSTING_UI_Security_User_IsAnonimous {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_User_IsAnonimous", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Is security started.
		/// </summary>
		internal static string OKHOSTING_UI_Security_User_IsSecurityStarted {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_User_IsSecurityStarted", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Secret answer.
		/// </summary>
		internal static string OKHOSTING_UI_Security_User_SecretAnswer {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_User_SecretAnswer", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Secret question.
		/// </summary>
		internal static string OKHOSTING_UI_Security_User_SecretQuestion {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_User_SecretQuestion", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a User log.
		/// </summary>
		internal static string OKHOSTING_UI_Security_UserLog {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_UserLog", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Date.
		/// </summary>
		internal static string OKHOSTING_UI_Security_UserLog_Date {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_UserLog_Date", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Id.
		/// </summary>
		internal static string OKHOSTING_UI_Security_UserLog_Id {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_UserLog_Id", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Operation.
		/// </summary>
		internal static string OKHOSTING_UI_Security_UserLog_Operation {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_UserLog_Operation", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a User.
		/// </summary>
		internal static string OKHOSTING_UI_Security_UserLog_User {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_UserLog_User", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a User permission.
		/// </summary>
		internal static string OKHOSTING_UI_Security_UserPermission {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_UserPermission", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a User.
		/// </summary>
		internal static string OKHOSTING_UI_Security_UserPermission_User {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_UserPermission_User", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a User session.
		/// </summary>
		internal static string OKHOSTING_UI_Security_UserSession {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_UserSession", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a End date.
		/// </summary>
		internal static string OKHOSTING_UI_Security_UserSession_EndDate {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_UserSession_EndDate", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Id.
		/// </summary>
		internal static string OKHOSTING_UI_Security_UserSession_Id {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_UserSession_Id", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Start date.
		/// </summary>
		internal static string OKHOSTING_UI_Security_UserSession_StartDate {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_UserSession_StartDate", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a User.
		/// </summary>
		internal static string OKHOSTING_UI_Security_UserSession_User {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Security_UserSession_User", resourceCulture);
			}
		}
	}
}
