//------------------------------------------------------------------------------
// <auto-generated>
//	 Este código fue generado por una herramienta.
//	 Versión de runtime:4.0.30319.42000
//
//	 Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//	 se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKHOSTING.UI.Resources {
	using System;
	using System.Reflection;
	
	
	/// <summary>
	///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
	/// </summary>
	// StronglyTypedResourceBuilder generó automáticamente esta clase
	// a través de una herramienta como ResGen o Visual Studio.
	// Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
	// con la opción /str o recompile su proyecto de VS.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class Strings {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Strings() {
		}
		
		/// <summary>
		///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OKHOSTING.UI.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
		///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a False.
		/// </summary>
		public static string OKHOSTING_UI_Controls_Forms_BoolField_False {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Controls_Forms_BoolField_False", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a True.
		/// </summary>
		public static string OKHOSTING_UI_Controls_Forms_BoolField_True {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Controls_Forms_BoolField_True", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Left.
		/// </summary>
		public static string OKHOSTING_UI_Controls_Forms_CaptionPosition_Left {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Controls_Forms_CaptionPosition_Left", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Top.
		/// </summary>
		public static string OKHOSTING_UI_Controls_Forms_CaptionPosition_Top {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Controls_Forms_CaptionPosition_Top", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a -.
		/// </summary>
		public static string OKHOSTING_UI_Controls_Forms_EmptyValue {
			get {
				return ResourceManager.GetString("OKHOSTING_UI_Controls_Forms_EmptyValue", resourceCulture);
			}
		}
	}
}
